name: Windows fast baseline SHDWN fixed

on:
  push:
    branches: [wd/fast-ef60c0d-shdwn-fix]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd c:\vcpkg ; git pull ; vcpkg install soapysdr:x64-windows
      - run: cmake -E make_directory ${{runner.workspace}}/build64-fast-shdwn
      - name: Configure
        shell: bash
        working-directory: ${{runner.workspace}}/build64-fast-shdwn
        run: cmake $GITHUB_WORKSPACE "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -A x64
      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build64-fast-shdwn
        run: cmake --build . --config $BUILD_TYPE --target SDDCSupport
      - name: SHA256
        shell: pwsh
        run: Get-FileHash "${{runner.workspace}}/build64-fast-shdwn/SoapySDDC/Release/SDDCSupport.dll" -Algorithm SHA256
      - uses: actions/upload-artifact@v4
        with:
          name: SDDCSupport-Windows-x64-fast-ef60c0d-shdwn-fixed
          path: ${{runner.workspace}}/build64-fast-shdwn/SoapySDDC/Release/SDDCSupport.dll
